archive and 1080p working

diff --git a/encode b/encode
--- a/encode
+++ b/encode
@@ -2,6 +2,7 @@
 set -euo pipefail
 IFS=$'\n\t'
 shopt -s nullglob
+shopt -s nocaseglob
 
 # test for ffmpeg in the path
 if ! hash "ffmpeg" >/dev/null 2>&1; then
@@ -17,26 +18,32 @@ fi
 
 # Define global variables and set defaults
 INPUT_PATH="$PWD"
+OUTPUT_PATH="$PWD/encoded.mp4"
 ENCODE_ARCHIVE=1
+HD_ARCHIVE=1
 
 # print out usage
 usage() {
   cat <<EOF
-USAGE: ./encode -p /Volumes/zen/timelapse/
+USAGE: ./encode -p /Volumes/fast/timelapseSource -o /Volumes/fast/timelapseArchive.mp4
 OPTIONS:
    -p    Path to source images
+   -o    Path to output file including extension
    -a    Encode with archive format
+   -d    Encode with HD 1080p 60fps
    -h    Help
 EOF
   exit
 }
 
 # process options and arguments
-while getopts "p:ah" OPTION; do
+while getopts "p:o:adh" OPTION; do
   case $OPTION in
   h) usage && exit 1 ;;
   p) INPUT_PATH=$OPTARG ;;
+  o) OUTPUT_PATH=$OPTARG ;;
   a) ENCODE_ARCHIVE=0 ;;
+  d) HD_ARCHIVE=0 ;;
   esac
 done
 
@@ -46,22 +53,38 @@ if ! [[ -d $INPUT_PATH ]]; then
   exit 1
 fi
 
-# get the first jpg file in the provided path and get details on it
+## get the first jpg file in the provided path and get details on it
 get_info() {
-  FIRST_JPG=$(find ${INPUT_PATH} -maxdepth 1 -name '*.[Jj][Pp][Gg]' | head -n 1) || true
-  jpeginfo -i "$FIRST_JPG"
+  FIRST_JPG=$(find ${INPUT_PATH} -maxdepth 1 -name '*.JPG' | head -n 1) || true
+  if [[ -f "$FIRST_JPG" ]]; then
+    jpeginfo -i "$FIRST_JPG"
+  else
+    echo "Error: ${INPUT_PATH}/*.JPG not found!"
+  fi
 }
 
 get_info
-#echo $FIRST_JPG
-echo FIN
-exit 0
 
-# test for jpegs at the provided path
-if ! [[ FIRST_JPG=$(find -maxdepth 1 ${INPUT_PATH} *.[Jj][Pp][Gg] | head -n 1) ]]; then
-  echo "Error: ${INPUT_PATH}/*.jpg not found!"
+archive_encode() {
+  ffmpeg -y -r 60 -thread_queue_size 8192 -pattern_type glob -i "${INPUT_PATH}/*.JPG" -vcodec libx264 -crf 26 -tune fastdecode -preset slow -c:v libx265 -pix_fmt yuv420p -tag:v hvc1 ${OUTPUT_PATH}
+}
+
+hd_encode() {
+  ffmpeg -y -r 60 -thread_queue_size 8192 -pattern_type glob -i "${INPUT_PATH}/*.JPG" -vcodec libx264 -crf 22 -tune fastdecode -vf "scale=iw*min(1920/iw\,1080/ih):ih*min(1920/iw\,1080/ih), pad=1920:1080:(1920-iw*min(1920/iw\,1080/ih))/2:(1080-ih*min(1920/iw\,1080/ih))/2" -preset fast -c:v libx265 -pix_fmt yuv420p -tag:v hvc1 ${OUTPUT_PATH}
+}
+
+
+if [[ $ENCODE_ARCHIVE == 0 ]]; then
+  archive_encode
+  open ${OUTPUT_PATH}
 fi
 
-#jpeginfo $FIRST_JPG
 
+if [[ $HD_ARCHIVE == 0 ]]; then
+  hd_encode
+  open ${OUTPUT_PATH}
+fi
+
+# test for jpegs at the provided path
+echo FIN
 exit 0
